### ISSUE TITLE
Connection refused on Slack connection, intermittently

### ISSUE THREAD

**Issue by desktophero** [target/flottbot#187]
# Report

## What did you do?

Spent way too long troubleshooting an auth issue that wasn't

## What did you expect to happen?

Provide the actual error in this err handler:

https://github.com/target/flottbot/blob/main/remote/slack/remote.go#L75-L79

## What happened instead?

Feedback is that auth is either unauthorized or invalid. But the actual message is

`connection is refused`

## Screenshots

Full log:

```shell
Error getting authd: Post "https://slack.com/api/auth.test": dial tcp 54.229.52.185:443: connect: connection refused
```

In remote/slack/remote.go, I added:

```golang
		fmt.Printf("Error getting authd: %s\n", err)
```

in the error condition to get more details

## Your Environment

Please complete the following information):
 - Flottbot version: [e.g. 0.1.0] 0.8.0 (not quite switched to Socket)
 - OS: [e.g. macOS] macOs, but I'm using python 0.8.0 as base in my k8s deployment
 - OS version: [e.g. 10.13.6]
 - Bot YAML (see below) NA
 - Rule YAML (see below) NA

```yaml
name: radar
cli: false
chat_application: slack
slack_token: ${RADAR_SLACK_TOKEN}
debug: true
metrics: true
```

```yaml
# please paste contents of your rule, if applicable (remove any sensitive information!)
```

## Additional context

This is on startup ... still working through repro steps to see if there's something unique about my env

I'm opening this mostly focused on how maintainers are thinking about more/better feedback on errors. This is definitely not to troubleshoot my issue of `connection refused`. The current static feedback is making the real issue/cause painful to diagnose. I'm more than happy to submit a PR on some updates ... just looking for maintainer feedback first.

Thank you!

**Comment by wass3r** [comment]
Thanks for the issue and feedback and sorry for the trouble you're dealing with.

In this case we went with what we most commonly saw the culprit was, but following the codepath it looks it could surface other types of connection errors as well. I can see us returning `err` in the error message as part of the error message as you did, if that's what you're thinking. Maybe the messaging from Slack in the case where the token actually was invalid is clear enough to not craft our own message here at all. Happy to review any PRs or suggestions.

Generally, I think the goals it to simply provide whatever message is most useful to resolve an issue as quickly as possible. Sometimes the error returned by providers (like Slack) doesn't translate well to flottbot, ie. it doesn't point out a flottbot setting that might need investigating, etc. I'm sure there is a nice middle ground maybe.

Hope that answers the question.
