### ISSUE TITLE
Scheduler spec that utilize "/" will not work 

### ISSUE THREAD

**Issue by JordanSussman** [target/flottbot#20]
Cron specs that utilize `/` will not work.
* e.g. `*/1 * * * *` (at every minute) fails, but `0 * * * *` (at minute 0) works

This is because the golang package we use to create cron jobs [robfig](https://github.com/robfig/cron), does not support said cron spec syntax.

**Comment by wass3r** [comment]
so, in the [package we're using](https://godoc.org/github.com/robfig/cron), the first field is actually a mandatory _seconds_ field, so an expression like `0 */1 * * * *` works as intended. you can also see this in the author's __test_ file. `0 * * * *` works because that's every minute at second 0. it's a little odd because the author requires all six fields and you supplied five :man_shrugging: 

there is [cron.v2](https://godoc.org/gopkg.in/robfig/cron.v2) by the same author that makes the first field (seconds) not mandatory and behave as expected (confirmed via local testing). seems like the best of both worlds. behaves as expected by default and gives the ability to do something at the second interval if so desired. [the source for v2](https://github.com/robfig/cron/tree/v2) hasn't been updated in over 4 years - so there's that.

so, i think there are four options (at least):
1. update docs to explain syntax that deviates from standard crontab
1. ~update~downgrade to `cron.v2` and deal with commit drift between that and master
1. find an alternative package
1. submit potential improvement from commits in master as patches to the v2 tree and :crossed_fingers: 

thoughts? /cc @pa3ng @JordanSussman @sjqnn 

as is, the *bug* label is probably misplaced here.

**Comment by wass3r** [comment]
At the risk of sounding lazy, I'll throw a vote for 1) in the hat.

**Comment by sjqnn** [comment]
I deem @wass3r lazy & concur!

**Comment by wass3r** [comment]
just needed some time. the lib has been updated in the meantime. i got something in queue to address this and support both 5-field (standard) and 6-field patterns (quartz) that should fix this issue.
