### ISSUE TITLE
Convert from logrus to zerolog

### ISSUE THREAD

**Issue by JordanSussman** [target/flottbot#66]
We should probably start thinking of moving away from [logrus](https://github.com/sirupsen/logrus) in favor of [zerolog](https://github.com/rs/zerolog) for our Golang projects going forward. ZL is supposed to be faster, and have more functionality but IMO the big win is not having to worry about the `Sirupsen` `sirupsen` import collision that happens.

The performance benefits look to be somewhat sizable (pun intended) too

- https://github.com/rs/zerolog#benchmarks
- https://github.com/imkira/go-loggers-bench

**Comment by wass3r** [comment]
Yes, we have used zerolog elsewhere before - i had no issues with it

**Comment by alankan886** [comment]
Hi @wass3r, is this issue still available to work on? If so, I would be interested to work on this issue.

**Comment by wass3r** [comment]
@alankan886 yes, it is. i think the dust settled a bit on the Sirupsen issue, but still interested in seeing this happen 👍

**Comment by alankan886** [comment]
Hey @wass3r, I added the PR. I do want to point out that I removed `logJSON` from the bot model since zerolog is JSON log by default. But if you want prettier logging similar to logrus, zerolog does have `zerolog.ConsoleWriter` that can achieve that by sacrificing performance (not sure by how much).

Let me know if you have any questions or concerns, thank you!
